In [2]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity


In [3]:
a_ls = np.array([[1,2,3],[4,5,6]])
b_ls = np.array([[1,2,3],[7,8,9],[13,14,15],[4,5,6],[10,11,12]])

In [4]:
cosine_similarities = cosine_similarity(a_ls, b_ls)  # (108, num_researchers - 108)

In [5]:
cosine_similarities

array([[1.        , 0.95941195, 0.94625552, 0.97463185, 0.95125831],
       [0.97463185, 0.99819089, 0.99463673, 1.        , 0.99614986]])

In [6]:
test_a = np.array([[1,2,3]])
test_b = np.array([[7,8,9]])

cosine_similarity(test_a,test_b)

array([[0.95941195]])

In [13]:
top_k_indices = np.argsort(cosine_similarities, axis=1)[:, ::-1]  # 降順ソートし、上位20人を取得

# 各行を降順にソート
sorted_similarities = np.sort(cosine_similarities, axis=1)[:, ::-1]

In [14]:
top_k_indices,sorted_similarities

(array([[0, 3, 1, 4, 2],
        [3, 1, 4, 2, 0]]),
 array([[1.        , 0.97463185, 0.95941195, 0.95125831, 0.94625552],
        [1.        , 0.99819089, 0.99614986, 0.99463673, 0.97463185]]))

In [41]:
b_ls[[2,0,4,3]]

array([[13, 14, 15],
       [ 1,  2,  3],
       [10, 11, 12],
       [ 4,  5,  6]])